// <auto-generated />
using System;
using AlertaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertaService.Migrations
{
    [DbContext(typeof(AlertaDbContext))]
    [Migration("20260208170500_criacaobancodados")]
    partial class criacaobancodados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertaService.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TalhaoId")
                        .HasColumnType("int");

                    b.Property<double>("ValorUmidade")
                        .HasColumnType("float");

                    b.Property<double>("ValorVento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
